### ISSUE TITLE
Is it possible to add a parameter to change the wallpaper every x minutes?

### ISSUE THREAD

**Issue by okon3** [ssimunic/Daily-Reddit-Wallpaper#3]
I really like my wallpaper to change while I work. I think this one would be a nice addiction without much effort.

**Comment by wynro** [comment]
You can do this via cron if you are in Linux

**Comment by ssimunic** [comment]
>

**Comment by ssimunic** [comment]
Exactly as @wynro said, this can be done using cronjobs.

Note that you can also use `--time hour` for top hourly images. I think that changing it every minute to newest submission wouldn't be safe, but I'll see which features I can add related to this.

**Comment by ssimunic** [comment]
I've added `--time new` for newest subreddit post.

**Comment by joesanford** [comment]
I can add a PR to keep the script running and make the change every x mins/hours/etc if you wish to re-open this.

**Comment by ssimunic** [comment]
Sure @joesanford you can add it!

**Comment by ssimunic** [comment]
Closing this, as its better solution to do this via cron or task scheduler than have the script running whole time.

**Comment by asgoel** [comment]
do you have an example crontab? keep getting the "Unsupported desktop environment" error when I run on my Ubuntu machine

**Comment by joesanford** [comment]
@asgoel does the script work if you just run it instead of as a cron job, or does it get the same error?

**Comment by asgoel** [comment]
Works fine if I run it normally. Think it has to do with the environment
that the cron job runs in

**Comment by joesanford** [comment]
That was my thought exactly.

Instead of having the script detect the environment when running as a cron job, I'd instead explicitly set the environment.
