### ISSUE TITLE
Script should not assume that the file is always jpg

### ISSUE THREAD

**Issue by dolohow** [ssimunic/Daily-Reddit-Wallpaper#30]

**Comment by jenroper** [comment]
That might be a good point, however, I'm having trouble finding an image subreddit that doesn't have a jpg file for its top post.  Could you point me to a test case?

**Comment by dolohow** [comment]
https://www.reddit.com/r/wallpapers/comments/6ygcbj/appa_1920x1200/

**Comment by jenroper** [comment]
It still sets your background to that image, but I see what you mean.

**Comment by dolohow** [comment]
It does not on KDE, just black screen.

**Comment by jenroper** [comment]
I think I've got it fixed on my fork, if you want to give it a try.
Although, to warn, I updated the script to work with a newer version of praw.  You need to register the script as app on your reddit account, and add your client id and client secret to the praw.ini file.  Instructions are in the readme.

**Comment by dolohow** [comment]
I fixed it as well -> 07dcadb :)
