### ISSUE TITLE
Accept a parameter for subreddit

### ISSUE THREAD

**Issue by Justinzobel** [ssimunic/Daily-Reddit-Wallpaper#34]
So you can pick the subreddit on each run. I like using earthporn. I've just manually changed it in the code for now but would be easier for the casual end-user.

**Comment by jenroper** [comment]
You can pass it a subreddit in the command line when you run it.  
Example

`python change_wallpaper_reddit.py --subreddit EarthPorn`

or

`python change_wallpaper_reddit.py --subreddit spaceporn --time week` 
for the weekly top image in the spaceporn subreddit

**Comment by Justinzobel** [comment]
Damnit, sorry to waste your time, I see it's in the README.md
